INSERT INTO `client` (client_id, secured)
VALUES (1, true),
       (2, false),
       (3, true),
       (4, false),
       (5, true),
       (6, true),
       (7, true),
       (8, true),
       (9, false),
       (10, true),
       (11, false),
       (12, true),
       (13, true),
       (14, true),
       (15, true),
       (16, false),
       (17, true),
       (18, false),
       (19, true),
       (20, true),
       (21, true);
